### ISSUE TITLE
New Colour causing issues.

### ISSUE THREAD

**Issue by Strandxo** [Danktuary/vuepress-theme-yuu#14]
text inside a Code element is purple constantly whilst in dark theme mode.
https://gyazo.com/27757e6a9fd91cc94c640fa8b151aca7

**Comment by Danktuary** [comment]
This is actually intentional; I made the inline codeblocks purple when first making the dark theme. It just one of the first decent colors that came to mind. But they do change colors depending on the selected theme if they're a link: https://gfycat.com/paleshadyisopod
You can also see that the regular purple inline code color and the purple theme color are slightly different.

I wouldn't recommend doing so, but if you want to alter this yourself to fit each theme, you can add your own CSS to overwrite it. Something like this:

```css
.yuu-theme-red .theme-default-content code {
	color: #de3636;
}

.yuu-theme-blue .theme-default-content code {
	color: #2196f3;
}

/* etc... */
```
